### PR TITLE
Audio error handling

### LINKED ISSUE #107: Handle autoplay exceptions
Hey,

newer browsers need a permission to play audio automatically on site load. [I've made an audio player](https://gitea.ksol.io/karolyi/karolyimusic-webplayer) that remembers its latest play state and resumes playing on site reload. If the site doesn't have the autoplay enabled, calling `play()` will result in an unhandled promise exception:

image

Console message: Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

You might want to look into this and handle the exception properly so I can act on it from within my player code.

Thanks!

### PR DESCRIPTION
**Pull request by eshaz**
## Features
* Send audio element `play()` and `pause()` errors through the `onError` callback. Resolves #107 
* `onError` callback always receives `Error` object as second parameter if present.

### CODE REVIEW

**Comment by karolyi** [comment]
Hey,

so I'm testing this with my code and I see that the `DOMException` is passed as a second parameter, next to a textual first parameter.

Is this always to be expected the case? I encourage this practice because the exception is actually something I can use to look up where the problem exactly lies.

**Comment by eshaz** [comment]
> Hey,
> 
> so I'm testing this with my code and I see that the `DOMException` is passed as a second parameter, next to a textual first parameter.
> 
> Is this always to be expected the case? I encourage this practice because the exception is actually something I can use to look up where the problem exactly lies.

@karolyi That's great feedback, and I completely agree. I've updated the `onError` callback so that it will always have the error object as the second parameter if there was an exception.

**Comment by karolyi** [comment]
Thanks!

I think you made a mistake though, as with your recent change, I get the following textual message: `The audio element encountered an error.undefined`

**Comment by eshaz** [comment]
> Thanks!
> 
> I think you made a mistake though, as with your recent change, I get the following textual message: `The audio element encountered an error.undefined`

It should look better now.

**Comment by karolyi** [comment]
Looks better thanks.

Just out of curiosity (and proper type checking in TS), that second parameter is not always a DOMException, depending on what happened, right?

**Comment by eshaz** [comment]
> Just out of curiosity (and proper type checking in TS), that second parameter is not always a DOMException, depending on what happened, right?

That's correct. The value passed as the second parameter should always be an `Error` type, if present, but it's not guaranteed to be any specific type of error. For the Audio element error handling, it's dependent what type is actually thrown by the browser, and also on reason / situation that caused the error.

**Comment by karolyi** [comment]
Alright, thanks.

I've managed to update my webplayer code so that it notifies upon autoplay error.

If you release your module update, I will be able to deploy as well. :)

**Pull request merged**
